#!/bin/bash

test_healthcheck() {
  echo ""
  container_id="$(docker ps | grep docker-healthcheck-test_app | awk '{print $1}')"
  if [ ! -z $container_id ]; then
    health="$(docker inspect $container_id | jq -r '.[].State.Health.Status')"
    outstr="[$(date +"%Y-%m-%d %H:%M:%S %Z")] Container $container_id : health = '${health}'"
  
    curl -f -s http://localhost:4047/ > /dev/null
    if [ $? -eq 0 ]; then 
      echo "${outstr} : responding = YES"
    else
      echo "${outstr} : responding = NO"
    fi
    if [ $health = "unhealthy" ]; then
      echo "Last healthcheck output:"
      echo "$(docker inspect $container_id | jq -r '.[].State.Health.Log[0].Output')"
    fi
  else
    echo "Container not found. Did you start it yet?"
  fi
}

while sleep 1; do test_healthcheck; done